name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
      - beta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Deploy main branch
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir -p public
        cp -R * public
        touch public/.nojekyll
        echo 'main' > public/CNAME
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Deploy beta branch
      if: github.ref == 'refs/heads/beta'
      run: |
        mkdir -p public/beta
        cp -R * public/beta
        touch public/beta/.nojekyll
        echo 'beta' > public/beta/CNAME
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/beta'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public/beta
